### ISSUE TITLE
withdraw-multi-token

### ISSUE THREAD

**Issue by krlosMata** [hermeznetwork/commonjs#27]
Check feature in [this issue](https://github.com/hermeznetwork/circuits/issues/40)

## Overview changes
- add `utils-multi-token-withdraw.js` functions to properly retrieve data to be used when using this feature

**Comment by laisolizq** [comment]
Spec WithdrawMultiToken: https://hackmd.io/6tABzjVKT4iX8W9_NhynOw

**Comment by krlosMata** [comment]
implemented in https://github.com/hermeznetwork/commonjs/pull/36
